# Generated by Django 4.1 on 2022-08-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facility_name", models.CharField(max_length=500)),
                ("street", models.CharField(max_length=500)),
                ("number", models.IntegerField()),
                ("postal_code", models.CharField(max_length=5)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                (
                    "surface_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("ownership", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="facility",
                        to="ASSETS.company",
                    ),
                ),
            ],
        ),
    ]
