# Generated by Django 4.1 on 2022-08-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0003_alter_facility_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="facility",
                to="ASSETS.company",
            ),
        ),
    ]
