# Generated by Django 4.1 on 2022-08-21 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0004_alter_facility_company"),
    ]

    operations = [
        migrations.RemoveField(model_name="facility", name="ownership",),
    ]
