# Generated by Django 4.1 on 2022-08-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0005_remove_facility_ownership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="image",
            field=models.ImageField(upload_to="pictures/facility"),
        ),
    ]
