# Generated by Django 4.1.1 on 2022-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0008_alter_facility_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="image",
            field=models.ImageField(null=True, upload_to="media/pictures/facility"),
        ),
    ]
