# Generated by Django 4.1.1 on 2022-09-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0009_alter_facility_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
