# Generated by Django 4.1.1 on 2022-09-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0010_alter_facility_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.CharField(max_length=30)),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor",
                        to="ASSETS.facility",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="floormodel",
            constraint=models.UniqueConstraint(
                fields=("floor", "facility"), name="unique_floor_per_facility"
            ),
        ),
    ]
