# Generated by Django 4.1.1 on 2022-09-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0012_roommodel_roommodel_uniqueconst_1_room_per_floor"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="facility",
            constraint=models.UniqueConstraint(
                fields=("company", "facility_name"),
                name="uniqueConst_1_facility_per_company",
            ),
        ),
    ]
