# Generated by Django 4.1.1 on 2022-09-29 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0014_equipmentfamilymodel_equipmentmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentfamilymodel",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="ASSETS.equipmentfamilymodel",
            ),
        ),
    ]
