# Generated by Django 4.1.1 on 2022-09-29 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0015_alter_equipmentfamilymodel_parent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmentmodel", old_name="parent", new_name="parent_id",
        ),
    ]
