# Generated by Django 4.1.1 on 2022-09-29 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0016_rename_parent_equipmentmodel_parent_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentmodel",
            name="parent_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="ASSETS.equipmentmodel",
            ),
        ),
    ]
