# Generated by Django 4.1.1 on 2022-09-29 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0017_alter_equipmentmodel_parent_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="equipmentmodel", old_name="family", new_name="family_id",
        ),
        migrations.RenameField(
            model_name="equipmentmodel", old_name="room", new_name="room_id",
        ),
    ]
