# Generated by Django 4.1.2 on 2022-11-30 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0018_rename_family_equipmentmodel_family_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_type", models.CharField(max_length=40)),
                ("code", models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name="roommodel",
            name="number",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="roommodel",
            name="room_type",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="room",
                to="ASSETS.roomtypemodel",
            ),
            preserve_default=False,
        ),
    ]
