# Generated by Django 4.1.2 on 2022-12-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0021_alter_roomtypemodel_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="roommodel", name="number",),
        migrations.AlterField(
            model_name="roommodel",
            name="room",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
