# Generated by Django 4.1.2 on 2022-12-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0022_remove_roommodel_number_alter_roommodel_room"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="roommodel", name="uniqueConst_1_room_per_floor",
        ),
        migrations.AddIndex(
            model_name="roommodel",
            index=models.Index(fields=["room"], name="ASSETS_room_room_7875c4_idx"),
        ),
    ]
