# Generated by Django 4.1.2 on 2023-01-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0024_floormodel_assets_floo_floor_36f315_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='roommodel',
            name='ASSETS_room_room_7875c4_idx',
        ),
        migrations.AddIndex(
            model_name='equipmentmodel',
            index=models.Index(fields=['name', 'parent_id', 'room_id', 'family_id'], name='ASSETS_equi_name_6fabfc_idx'),
        ),
        migrations.AddIndex(
            model_name='roommodel',
            index=models.Index(fields=['room', 'floor', 'room_type'], name='ASSETS_room_room_5c2b3a_idx'),
        ),
    ]
