# Generated by Django 4.1.1 on 2022-10-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("WORKS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobTypeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
