# Generated by Django 4.1.2 on 2022-10-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WORKS", "0003_jobmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobmodel", old_name="domain", new_name="domain_id",
        ),
        migrations.RenameField(
            model_name="jobmodel", old_name="job_type", new_name="job_type_id",
        ),
    ]
