# Generated by Django 4.1.2 on 2022-10-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("WORKS", "0006_workordermodel_workstatusmodel_workorderstatusmodel_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="workordermodel", name="assigner",),
        migrations.AddField(
            model_name="workordermodel",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assignee_wo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
