# Generated by Django 4.1.2 on 2022-12-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WORKS", "0009_alter_jobmodel_description_alter_jobmodel_domain_id_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="jobmodel", old_name="name", new_name="job",),
    ]
