# Generated by Django 4.1.2 on 2022-12-06 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ASSETS", "0024_floormodel_assets_floo_floor_36f315_idx"),
        ("WORKS", "0010_rename_name_jobmodel_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workordermodel",
            name="equipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ASSETS.equipmentmodel",
            ),
        ),
    ]
