# Generated by Django 4.1.2 on 2023-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0011_alter_workordermodel_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
