# Generated by Django 4.1.2 on 2023-01-02 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0024_floormodel_assets_floo_floor_36f315_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WORKS', '0012_alter_workordermodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workordermodel',
            name='domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='WORKS.domainmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='WORKS.jobmodel'),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='job_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='WORKS.jobtypemodel'),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reporter_wo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_order', to='ASSETS.roommodel'),
        ),
        migrations.AlterField(
            model_name='workordermodel',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='WORKS.workstatusmodel'),
        ),
    ]
