# Generated by Django 4.1.2 on 2023-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0014_workstatusmodel_position_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='workstatusmodel',
            index=models.Index(fields=['name', 'position'], name='WORKS_works_name_7483e2_idx'),
        ),
    ]
