# Generated by Django 4.2 on 2023-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0020_workorderstatusarchivemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderstatusarchivemodel',
            name='work_order',
            field=models.IntegerField(),
        ),
    ]
