# Generated by Django 4.2 on 2023-05-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0021_alter_workorderstatusarchivemodel_work_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workorderarchivemodel',
            name='work_order_archive_idx',
        ),
        migrations.AddIndex(
            model_name='workorderarchivemodel',
            index=models.Index(fields=['title', 'room', 'job_type', 'status', 'equipment', 'reporter', 'assignee', 'job', 'domain', 'creation_date', 'start_date', 'end_date'], name='work_order_archive_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderstatusarchivemodel',
            index=models.Index(fields=['work_order', 'event_date_time', 'status_before', 'status_after', 'author'], name='work_order_status_archive_idx'),
        ),
    ]
