# Generated by Django 4.2 on 2023-05-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WORKS', '0022_remove_workorderarchivemodel_work_order_archive_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderHourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='WORKS.workordermodel')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_work_hours', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='workorderhourmodel',
            index=models.Index(fields=['work_order', 'worker', 'start_datetime', 'end_datetime'], name='WORKS_worko_work_or_1cda39_idx'),
        ),
    ]
