# Generated by Django 4.2 on 2023-05-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0023_workorderhourmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
