# Generated by Django 4.2 on 2023-06-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WORKS', '0024_jobmodel_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='workordermodel',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
