# Generated by Django 4.2 on 2023-06-14 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0025_remove_roommodel_assets_room_room_7875c4_idx_and_more'),
        ('WORKS', '0025_workordermodel_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobEquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='ASSETS.equipmentmodel')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='WORKS.jobmodel')),
            ],
        ),
    ]
