# Generated by Django 4.2 on 2023-06-14 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASSETS', '0025_remove_roommodel_assets_room_room_7875c4_idx_and_more'),
        ('WORKS', '0026_jobequipmentmodel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobequipmentmodel',
            unique_together={('job_id', 'equipment_id')},
        ),
    ]
